### ISSUE TITLE
Add support for SDMX

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/STATcubeR#27]
It would be very useful if `{STATcubeR}` could support "SDMX archives" which are generated from STATcube.  sdmx archives consist of a metadata component called the "structure definition" and a data part which contains the actual cell values. In order to support that, we would need to add parsers for the xml-based data format.

The generated archives are more or less compatible with the CRAN package rsdmx: https://cran.r-project.org/package=rsdmx, which could be used as a starting point to develop parsers. 

Possible usuage: parser function `sdmx_table()` which generates an object of class `sc_data` (the parent class for OGD and STATcube-API datasets)

```
x <- STATcubeR::sdmx_table("path/to/sdmx_archive.zip")
class(x)
#> [2] "sdmx_table" "sc_data" "R6"
```

There are several advantages of the sdmx format compared to the API 

* The structure definition contains information about hierarchical classifications, which are not available via the API
* The download option "sdmx archive" is available even if STATcube is used as a "guest user"
* SDMX is used by other SuperSTAR products such as SuperCROSS

The last point is probably the most compelling one since a direct interface to SuperCROSS would be very helpful for the internal workflows of statistics austria

**Comment by GregorDeCillia** [comment]
Screenshot: SDMX downloads are available for unregistered users on the external STATcube instance

![image](https://user-images.githubusercontent.com/9311130/187090864-7eb3e0a0-def8-4255-84e1-60d1d8f280e4.png)

**Comment by bernhard-da** [comment]
`sdmx_table()` is now exported
