### ISSUE TITLE
Did anybody try to request the data via Python?

### ISSUE THREAD

**Issue by JohnnyFruitbasket** [statistikat/STATcubeR#45]
So far, all I am able to do is produce "JSONDecodeError"s: "Expecting value: line 1 column 1 (char 0)"

I tried something like this:
```python
import requests

api_url = "https://statcubeapi.statistik.at/statistik.at/ext/statcube/rest/v1e/table"

api_key = "<quitesomekeyhere>"

headers = {'APIKey': api_key, "Content-Type": "application/json"}

query = {
  "database" : "str:database:debevstprog",
  "measures" : [ "str:statfn:debevstprog:F-BEVSTPROG:F-S25V1:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V2:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V3:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V4:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V5:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V6:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V7:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V8:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V9:SUM", "str:statfn:debevstprog:F-BEVSTPROG:F-S25V10:SUM" ],
  "recodes" : {
    "str:field:debevstprog:F-BEVSTPROG:C-C11-0" : {
      "map" : [ [ "str:value:debevstprog:F-BEVSTPROG:C-C11-0:C-C11-0:C11-1" ], [ "str:value:debevstprog:F-BEVSTPROG:C-C11-0:C-C11-0:C11-2" ] ],
      "total" : False
    },
    "str:field:debevstprog:F-BEVSTPROG:C-A10-0" : {
      "map" : [ [ "str:value:debevstprog:F-BEVSTPROG:C-A10-0:C-A10-0:A10-2000" ], [ "str:value:debevstprog:F-BEVSTPROG:C-A10-0:C-A10-0:A10-2010" ], [ "str:value:debevstprog:F-BEVSTPROG:C-A10-0:C-A10-0:A10-2020" ], [ "str:value:debevstprog:F-BEVSTPROG:C-A10-0:C-A10-0:A10-2030" ] ],
      "total" : False
    }
  },
  "dimensions" : [ [ "str:field:debevstprog:F-BEVSTPROG:C-A10-0" ], [ "str:field:debevstprog:F-BEVSTPROG:C-C11-0" ] ]
}

response = requests.get(api_url, headers=headers, params=query)
response_data = response.json()
print(response_data.text)
```

Also had to replace the "false" in the JSON query with "False", as the IDE was throwing an error otherwise. I am not the most firm with REST APIs, can anybody offer some insight how this might work?

**Comment by GregorDeCillia** [comment]
I don't think `params` is the way to pass the json payload. I am not familiar with python, but I think `params` will convert the data from `query` into query parameters while the API expects the data in the request body. Also, POST is the expected http verb for the `/table` endpoint, not `GET`. According to [this SO question](https://stackoverflow.com/questions/9733638/how-to-post-json-data-with-python-requests), this should work.

```py
requests.post(api_url, headers=headers, json=query)
```

**Comment by JohnnyFruitbasket** [comment]
Thanks, that was quite useful. I made some changes (turns out, there is an json parameter in the .post method) and this does it for me:
```Python
response = requests.post(api_url, headers=headers, json=query)
print(response.status_code)
response_data = response.json()
print(response_data)
```
Got a positive status code and the requested data

**Comment by GregorDeCillia** [comment]
It's a convention that `GET` requests only pass request-data via query-parameters. That's why the `json` parameter is not available in `.get()` but available in `.post()`. Anyways, glad to hear this is working for you now. In case this comes up: invalid JSON and rate limits might generate misleading error messages. I've written up a guide for this in https://statistikat.github.io/STATcubeR/dev/articles/sc_last_error.html#invalid-json.
